# -*- coding: utf-8 -*-
"""Boot camp project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MA_HtGcA-19O0X3ZGfD_ADFvq7gJeikr
"""

import hashlib
x= input ("Enter a string to convert it into mD5: ")
y= hashlib.md5 (x.encode())
print(x,"in mD5 is:", y.hexdigest() )