# -*- coding: utf-8 -*-
"""Boot camp project ques 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MA_HtGcA-19O0X3ZGfD_ADFvq7gJeikr
"""

import hashlib
x=input("Enter a string: ")
a= hashlib.sha1(x.encode())
print ("String in sha1:",a.hexdigest())
b= hashlib.sha224(x.encode())
print("String in sha224:",b.hexdigest())
c= hashlib.sha256(x.encode())
print("String in sha256:",c.hexdigest())